cluster.name: "docker-cluster"
network.host: 0.0.0.0
http.port: 9200

# Fix para CORS y acceso
http.cors.enabled: true
http.cors.allow-origin: "*"

# Paths
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
